# This file intentionally left blank
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
CAPS_WORD_ENABLE = yes
SWAP_HANDS_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
CONSOLE_ENABLE = yes
KEY_LOCK_ENABLE = yes
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor